version: '3.8'

services:
  meow_db:
    image: mysql:8.0.30
    container_name: meow_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wypozyczalnia_ksiazek
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - meow_network

  meow_app:
    image: meow_web_app
    container_name: meow_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=meow_db;port=3306;database=wypozyczalnia_ksiazek;user=root;password=rootpassword;
    volumes:
      - ./data-protection-keys:/root/.aspnet/DataProtection-Keys
    
      - ./wwwroot/images:/app/wwwroot/images
    depends_on:
      - meow_db
    networks:
      - meow_network

volumes:
  mysql_data:

networks:
  meow_network:
    driver: bridge